# Generated by Django 3.0.5 on 2020-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=225)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=400)),
                ('imagen', models.CharField(max_length=400)),
                ('ingredientes', models.ManyToManyField(blank=True, related_name='hamburguesas', to='productos.Ingrediente')),
            ],
        ),
    ]
